# File: .github/workflows/main.yml
name: Deliver container to Okteto

on: push

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Create namespace
      uses: okteto/create-namespace@latest
      with:
        namespace: pr-${{ github.event.number }}-rmetdep
   
    - name: Deploy application
      uses: okteto/deploy-stack@latest
      with:
        build: "true"
        namespace: pr-${{ github.event.number }}-rmetdep